### ISSUE TITLE
Tile borders visible when scaled in

### ISSUE THREAD

**Issue by Nohus** [peterLaurence/MapCompose#14]
This is a separate issue from #5, which wasn't previously obvious because the other issue was showing up at the same time. But now that the other issue is fixed this one can be seen.

When the map is scaled in past `1f`, the tiles become blurred – this is expected. However because the tiles are blurred individually and then drawn separately, the blur does not cross tile borders, which makes the tile borders visible:

![image](https://user-images.githubusercontent.com/11064768/143080006-261183a5-7e4f-4281-9eb3-a2c1fca282dc.png)

The tiles probably need to be drawn without scaling to a buffer, and then the entire buffer drawn in scaled, or some similar approach.

**Comment by peterLaurence** [comment]
Drawing to a buffer (e.g assembling a big image of the size of the screen) goes against the tiling philosophy. Also, that would be quite inefficient regarding memory usage (if we scroll a bit to the right, then back to left, then to the right again..).
Unless there's a Paint setting that would fix that effect, I don't see what more can be done here. 
A possibility would be a new feature: add a background image that scales with the map, and make tiles disappear past scale 1f.

**Comment by Nohus** [comment]
Sure, this is not a big issue and only appear at high scale levels, but just reporting since I notices it. :+1:
