### ISSUE TITLE
Scale-dependent bitmap filtering

### ISSUE THREAD

**Issue by Nohus** [peterLaurence/MapCompose#17]
I have added a configuration for bitmap filtering in #15, which makes pixel art style images look much better when scaled in a lot. However I found that it makes them look worse when scaled out a lot...
After some testing I can see that at least for my use case, it would be best to have bitmap filtering disabled for scale > 1, and enabled for scale < 1. I am wondering what is the API for enabling that you'd accept in a PR.

Currently we have this:
```Kotlin
fun MapState.setBitmapFilteringEnabled(enabled: Boolean) {
    isBitmapFilteringEnabled = enabled
}
```

My current idea is to add another method like this, which enables to select the filtering state based on the current map scale:
```Kotlin
fun MapState.setBitmapFilteringEnabled(predicate: (scale: Float) -> Boolean)
```

This would enable my client to do:
```Kotlin
state.setBitmapFilteringEnabled { scale -> scale < 1 } 
```

What do you think?

**Comment by peterLaurence** [comment]
More generally, the predicate could be a lambda with `MapState` as receiver type:

```kotlin
fun MapState.setBitmapFilteringEnabled(predicate: MapState.() -> Boolean)
```

Filtering could now depend on scroll in addition to scale.
