### ISSUE TITLE
Layers support

### ISSUE THREAD

**Issue by Nohus** [peterLaurence/MapCompose#19]
I propose a layers feature that would allow to display multiple tile maps at the same time. Higher layers would use images with alpha so that the lower layers are still visible. Individual layer opacity would also be configurable.

**Use cases**
- Normal tile layer for a world map + weather tile layer with clouds that renders on top
- Ground level tile layer + layer for every architectural level on top
- Server-side data overlays over the base map
- Animated switching of map types/styles (add both maps as 2 layers, animate alpha, remove old layer)

**Usage**
From the API perspective, this could be a version/replacement of `TileStreamProvider` that returns multiple tiles (`List<InputStream>`). There would also need to be a way to control a layers' alpha; this could be either defining the layers and their alpha separately, or as part of the `TileStreamProvider`.

There is also a case to be made that this is something the client code could do, and not a library feature: blend the multiple tiles yourself and provide the composite tile to `TileStreamProvider`. The issue with that with the current API is that `TileStreamProvider` wants an `InputStream`, which is difficult to work with if the client code was to generate tiles dynamically. Presumably the tiles were already read from whatever `InputStream`s and blended into the final `Bitmap`, so `TileStreamProvider` would need to work with `Bitmap`s, not `InputStream`s.

It would definitely be nicer as a proper library feature though.

For reference, here is the feature in Google Maps SDK: https://developers.google.com/maps/documentation/android-sdk/tileoverlay
In OsmDroid: https://osmdroid.github.io/osmdroid/Map-Sources.html (Can I use more than one tile source at a time? section)

What do you think?

**Comment by peterLaurence** [comment]
I have implemented layering in my trekking app, using a custom `TileStreamProvider`. Have a look at https://github.com/peterLaurence/TrekMe/blob/master/app/src/main/java/com/peterlaurence/trekme/core/providers/stream/TileStreamProviderOverlay.kt

In this implementation, the tile from the primary layer is fetched, then loaded into a `Bitmap`n itself drawn into a `Canvas`. For each overlay layers, bitmaps are drawn onto that bitmap. Then an `InputStream` is made from the resulting bitmap (don't pay too much attention to the custom `TileResult` type -- it's just a wrapper).

Before continuing the discussion, let me know what you think of this approach.

**Comment by Nohus** [comment]
That's what I envisioned with the client-side implementation, great to see a working example! But it seems to have the problem I talked about with `TileStreamProvider` requiring an `InputStream`. You have to compress the `Bitmap` to a PNG, so then the library has to decode it back again. Surely that's not great for performance?

**Comment by peterLaurence** [comment]
Well, if that's not done client side, the exact same code will be done by the library. Unless I am missing something.
The fact that the `TileStreamProvider` returns an `InputStream` isn't a problem here. If it returned a `Bitmap` (which means that it would already be allocated), another `Bitmap` instance has to be allocated anyway to draw it onto the previous one.
Again, unless I am missing something.
BTW, there's a good reason why `TileStreamProvider` returns an `InputStream` and not a `Bitmap`. TileCompose internally use `Bitmap` pooling to optimize allocations. That implfies that `Bitmap` allocations aren't user managed. This obviously becomes useless when doing things like in my layering implementation.
Which.. bring me to the conclusion that some library optimizations could be done to avoid that. Yes.

**Comment by Nohus** [comment]
The `Bitmap` allocations must happen either way, yes, but what I mean is that after you have the final `Bitmap`, you are compressing it to PNG and then the library has to `decodeStream` it back into a `Bitmap`. I think that compression-decompression step is unnecessary.

**Comment by peterLaurence** [comment]
Oh yes the compressing thing is propably not necessary. I don't remember why it's there.

**Comment by peterLaurence** [comment]
FYI : https://www.youtube.com/watch?v=_ioFW3cyRV0

I believe the library could do that no only for a single layer, but potentially with multiple `TileStreamProvider`.

**Comment by Nohus** [comment]
Although in case of implementing layers in the library, I was thinking of calling the drawing code for every layer, not creating a composite `Bitmap` and then drawing it. So draw both `Bitmap`s into the final `Canvas`, without an intermediate per-tile `Canvas` .

**Comment by peterLaurence** [comment]
> Although in case of implementing layers in the library, I was thinking of calling the drawing code for every layer, not creating a composite Bitmap and then drawing it. So draw both Bitmaps into the final Canvas, without an intermediate per-tile Canvas .

Not only that, but also reuse as many as `Bitmap` instances as necessary.

**Comment by Nohus** [comment]
Also that, yes!

**Comment by peterLaurence** [comment]
Alright. I'll have stab at this one. It will impact the core of the library.

**Comment by peterLaurence** [comment]
I remember why there's a PNG compression. The resulting stream isn't used for MapCompose, but for making PNGs image files.
Those files (tiles) are later read to show the map on screen, so all the layering thing is already done because every tiles are made of several blended images. On the good side, it's impossible to be more performant. The downside is that it's not dynamic. It's impossible to dynamically change the opacity of a layer.
So that's the approach I had in my app.

**Comment by Nohus** [comment]
I see. For my use case I'd definitely need per-layer opacity control. I want the user to be able to control the layers they enable and their opacity (think current and historical map layer, with user being able to control which one they see and how much, to compare them). I don't have caching implemented yet, but I'd cache the tile files separately, so I would also be able to avoid the additional compression step when showing the map, if the library allowed it.

**Comment by peterLaurence** [comment]
That's clear now. A library support is necessary when things need to be dynamic.

**Comment by peterLaurence** [comment]
I've started thinking about it, and realized it'll require major changes to the core. However, I'd like to finish other work before diving into this. Can it wait a few weeks?

**Comment by Nohus** [comment]
I'm sure I can reorganize my to do list to work on other app features than the one I need the layers for. : ) Wouldn't want to put any pressure on your voluntary work, the library is a huge help to me as it is!

**Comment by Nohus** [comment]
I was commenting on commits to catch them before they appear on `master`, ideally I'd comment on a PR, if there is going to be one.

**Comment by peterLaurence** [comment]
No problem! For the moment it's still WIP (sometimes, I revert something I did before). It's a bit too soon for a global code review, but thanks for your early comments. It helps to know your expectations early.

**Comment by peterLaurence** [comment]
The plan is to finish the APIs, make a dedicated demo, and let you know when you can evaluate this `layer` branch. Once I get you feedback, I'll make necessary changes (if any). Then, I'll create a `v2` branch from master and make breaking changes like the suspending `TileStreamProvider`, update compose to 1.1.0 (beta), etc.
I believe layers will land in 2.0.0

**Comment by peterLaurence** [comment]
The `layers` can now be tested. For the moment, don't use `addLayer` api (I haven't tested it yet). The others worked per my tests.
For each individual issues that may (ok.. will) arise, we will create separate issues. For example, I'm expecting that you get the blank screen again. However, for this one, I have a fix candidate very similar to what you've done on master (it's a shared flow, but a replay of 1). We'll see.
For all other issues, it's import to try as hard as we can to _reproduce on the demo_.

**Comment by Nohus** [comment]
The first issue, like you said, is the blank screen. This is related to `scale`. No tiles are drawn when `scale >= 1`. If I initialize the map with `scale < 1` it works from the start, but as soon as it scaled in past 1 tiles disappear.
Can you reproduce this one or should I try to investigate / reproduce on the demo app?

**Comment by peterLaurence** [comment]
I can't reproduce the scale issue in the demo. In the demo, it scales up to 2f (the max scale by default). Even increasing the max scale to 4, it works in the demo.

**Comment by peterLaurence** [comment]
Ok I'm creating an issue.

**Comment by peterLaurence** [comment]
Here's my suggestion for the layers API changes we discussed earlier.

Instead of having to specify an id when adding a layer, the id is created by the library using an UUID. The created id is returned by the API (let's say `addLayer`).
This id is important to keep, because it's necessary to use other APIs such as `moveLayerUp`, `moveLayerDown`, etc.
The consequence of this, which isn't a big deal but worth to notice since it's a breaking change : it's no longer required to pass a `TileStreamProvider` to the `MapState` constructor (because the user may need to know the id of this implicitly created layer).

That way, there's concept of "primary layer". Everything is a layer.
The library will apply default rules like :
1. The lowest layer has an opacity of 1 and cannot be changed dynamically
2. Removing layers defaults to removing all layers except the lowest one

Note that any layer can become the lowest one dynamically.
A new API would be handy: `replaceLayer(id)`. Which would be the equivalent of the current `setPrimaryLayer` (if of course the id corresponds to the lowest layer).

**Comment by Nohus** [comment]
I like this much more!

**Comment by peterLaurence** [comment]
This is done. I'll now create a separate testing app.
