### ISSUE TITLE
redrawTiles() sometimes clears the map and does not redraw tiles

### ISSUE THREAD

**Issue by Nohus** [peterLaurence/MapCompose#20]
I am currently investigating an issue where `redrawTiles()` sometimes does not trigger a redraw, only clears the map.

In a successful redraw, `visibleTilesFlow` gets set to `null`, that gets collected, then to the new `VisibleTiles`, which gets collected and redrawn.
Sometimes, `visibleTilesFlow` gets sets to `null`, and then `VisibleTiles`, as normal, but neither are collected. For some reason the `visibleTilesFlow` emissions are ignored by the collector. I am still investigating why, but maybe you have an idea.

This only seems to happen when `redrawTiles()` is called quickly after a previous call, maybe up to 2 seconds. It may just be that it can only happen when the tiles are still loading when another `redrawTiles()` call is made.

**Comment by peterLaurence** [comment]
It's most probably because `tileCanvasState` received the same `VisibleTiles` object it already received a few milliseconds ago. 
That should be easy to fix. Thanks.

**Comment by peterLaurence** [comment]
Turns out, I couldn't reproduce. The potential issue I mentioned isn't possible, because inside `TileCanvasState::clearVisibleTiles`, there's a reset : `visibleTilesFlow.value = null`. So any new api call will trigger an update.
Stress testing inside a demo, using:

```kotlin
init {
   viewModelScope.launch {
       delay(4000)
       while (true) {
           state.redrawTiles()
           delay(200)
           state.redrawTiles()
       }
   }
}
```

Playing with the delay (5 to 2000 or more), couldn't see blank screen. Are you sure the problem doesn't come from your `TileStreamProvider`?

**Comment by Nohus** [comment]
> Are you sure the problem doesn't come from your `TileStreamProvider`?

Yes, because when the problem occurs my `TileStreamProvider` isn't called at all.

Here are some logs I added to the library:

```
redrawTile() called
2021-12-04 07:58:29.490 7368-7554/[..].debug E/MapCompose: Emitting null
2021-12-04 07:58:29.490 7368-7554/[..].debug E/MapCompose: Collecting: null
2021-12-04 07:58:29.491 7368-7554/[..].debug E/MapCompose: Emitting new tiles: VisibleTiles([..])
2021-12-04 07:58:29.495 7368-7554/[..].debug E/MapCompose: Collecting: VisibleTiles([..])
redrawTile() called
2021-12-04 07:58:30.456 7368-7554/[..].debug E/MapCompose: Emitting null
2021-12-04 07:58:30.456 7368-7554/[..].debug E/MapCompose: Emitting new tiles: VisibleTiles([..])
```

I called `redrawTiles()` tiles twice, the first one worked fine, there were two emissions and two collections. After the second call, there were two emissions again, but they were not collected and the map just turned blank.

**Comment by peterLaurence** [comment]
I can imagine some scenario where that could happen. That involves scrolling or zooming while calling `redrawTiles` repeatedly.

**Comment by peterLaurence** [comment]
Confirmed.

**Comment by Nohus** [comment]
I think it's because the collector is still busy when the `null` emission happens, so it's ignored, and then when the `VisibleTiles` are emitted, they are ignored again because they are identical to the last ones that were emitted. I call `redrawTiles()` because I switch tiles in my `TileStreamProvider`, but the `VisibleTiles` doesn't change.

**Comment by Nohus** [comment]
Yeah, when I force `VisibleTiles` to always be unique the bug never happens, so that will be it.

**Comment by peterLaurence** [comment]
Sure, but triggering the rendering logic at every `VisibleTiles` emission isn't ideal. I'm working on a workaround which doesn't change that. I Couldn't reproduce the issue, but still figure out why it works haha.

**Comment by Nohus** [comment]
> Sure, but triggering the rendering logic at every VisibleTiles emission isn't ideal.

Of course, this was just to test what happens.

**Comment by Nohus** [comment]
I may have fixed it, just doing some additional testing.

**Comment by Nohus** [comment]
> I Couldn't reproduce the issue

Did you try a `TileStreamProvider` with a `delay(500)` inside?

**Comment by peterLaurence** [comment]
I believe this is because there's an interleaving between multiple coroutines who attempt to trigger new tiles render. There is the "throttled" coroutine corresponding to zoom and pan, and there's the one manually launched with `redrawTiles`. Depending on their interleaving, when we call `redrawTiles`, a race condition on `visibleTilesFlow` can actually push a non null value of `VisibleTiles`. Immediately after, when `redrawTiles` tries to push a new value on the state flow, it pushes the same value...

So my "fix" is to make the `redrawTiles` atomic (coroutines-wise). I'm pushing a branch `try-fi-#20`. Let me know if you reproduce using this branch.

**Comment by peterLaurence** [comment]
> Did you try a TileStreamProvider with a delay(500) inside?

I'm doing it right now.

**Comment by peterLaurence** [comment]
> Of course, this was just to test what happens. I think the real solution is to replace the "allow duplicate emissions on a StateFlow with a null emission in-between" with something else.

That's an interesting idea

**Comment by Nohus** [comment]
Your change didn't fix it.

**Comment by Nohus** [comment]
But this does.

**Comment by Nohus** [comment]
The concern with that is that now duplicate emission will needlessly render again, if I understand correctly.

**Comment by peterLaurence** [comment]
Hmm.. ok I'll try to improve upon it, making `setVisibleTiles` a suspend function.

**Comment by peterLaurence** [comment]
Can you try just: 

```
private suspend fun setVisibleTiles(visibleTiles: VisibleTiles) {
        /* Feed the tile processing machinery */
        visibleTilesFlow.emit(visibleTiles)
```

the rest being identical

**Comment by Nohus** [comment]
I updated the PR, can you take a look? Now duplicate emissions are ignored as they were, but the `null` cannot be lost.

**Comment by peterLaurence** [comment]
I'm wondering if changing `visibleTilesFlow.value = visibleTiles` so suspend emission was necessary, after the shared flow change. Could you please try and tell me if that change was necessary?

**Comment by Nohus** [comment]
I'm not sure I understand? `SharedFlow` does not have a `value`.

**Comment by peterLaurence** [comment]
Oh yes, my bad.

**Comment by peterLaurence** [comment]
That's the kind of issue which is really hard to understand. I'm still trying to figure out the exact scenario that produced this issue.

**Comment by Nohus** [comment]
I think it's the `TileStreamProvider` being busy while both `null` and the new `VisibleTiles` emissions happen, and by the time it wants to collect the next value, the next value is the `VisibleTiles` already, which is same as last so it's ignored. What we changed  is that now that it's a `SharedFlow` emissions cannot get lost if there are multiple ones between collections.

At least that's my guess.

**Comment by peterLaurence** [comment]
> SharedFlow emissions cannot get lost if there are multiple ones between collections.

Yes, but there's a `distinctUntilChanged()`, which, in theory, makes the shared flow behave like a state flow.

**Comment by Nohus** [comment]
Yes, but now it's not affected by the collector being slow.

**Comment by peterLaurence** [comment]
Which part isn't affected?

**Comment by peterLaurence** [comment]
Perhaps the `collectLatest` wasn't working as I thought, and the state flow allowed a value to be replaced before making the comparison with the latest received value, and eventually cancel any ongoing processing (when the collector is slow).

**Comment by peterLaurence** [comment]
That might be it after all. A shared flow, by default, suspend on emissions. While a state flow does not. Apparently, this has consequences on what we expect from `collectLatest` operator.

**Comment by Nohus** [comment]
`SharedFlow` with `distinctUntilChanged()` is different from `StateFlow` because `StateFlow` replaces previous values, while the `SharedFlow` will "queue" all emissions. At least that's my understanding.

> Perhaps the `collectLatest` wasn't working as I thought

I think that although the concept is correct, coroutines cannot be cancelled at any point, and the `StateFlow` could update twice before the coroutine allowed itself to be cancelled so a new collection can happen.

**Comment by peterLaurence** [comment]
> the SharedFlow will "queue" all emissions. At least that's my understanding.

Unless you create it like that : MutableSharedFlow(1, 0, BufferOverflow.DROP_LATEST)

> I think that although the concept is correct, coroutines cannot be cancelled at any point, and the StateFlow could update twice before the coroutine allowed itself to be cancelled so a new collection can happen.

I agree.

**Comment by peterLaurence** [comment]
I'm back porting this inside the `layer` branch!

**Comment by peterLaurence** [comment]
In the `layer` branch, having a state flow is way more convenient, as it allows to check the current value without starting a new coroutine. I've found that we can atomically set a value on a state flow, using `update` extension functions available since kotlinx.coroutines 1.5.1.
Could you please try again my `try-fix-#20` branch? If that fixes the issue as well, that would be perfect, as otherwise I'll need more time to do the same with a shared flow.

**Comment by Nohus** [comment]
No, it doesn't fix it. :/

**Comment by peterLaurence** [comment]
out of curiosity, you're using the demo to reproduce it, or your app? I'd like to quickly reproduce like you do.

**Comment by Nohus** [comment]
But if a `StateFlow` is better then an alternative would be to distinguish between the "same" `VisibleTiles` across `redrawTile()` calls without the `null` value. A naive solution would be to increment a counter each time you would send a `null` in the current code, and include the counter in the `VisibleTiles` class. But there is surely a cleaner solution.

**Comment by Nohus** [comment]
I'm using my app.

**Comment by peterLaurence** [comment]
> I'll try reproducing it in the demo app.

Perfect

**Comment by peterLaurence** [comment]
If necessary, I'll also consider a different strategy, like you suggest.

**Comment by peterLaurence** [comment]
I've found a serious issue inside the `throttle` implementation. If the underlying channel was full, a call to `renderThrottle` wasn't actually triggering a new render. The fix is in the branch `rework-throttle`.
It might as well be a fix to #20, but it's hard for me to be sure. Thank you for volunteering in this, you're helping me a lot.

**Comment by Nohus** [comment]
`render-throttle` doesn't fix it. I couldn't easily reproduce the issue in the demo app, but I am still trying.

**Comment by peterLaurence** [comment]
Alright, `render-throttle` is fixing something nevertheless. Good to know.

**Comment by peterLaurence** [comment]
While I did manage to reproduce it multiple times on `rework-throttle`, I still haven't reproduced on `layer` branch. Thankfully, the api of the `layer` branch should still be compatible with your app - so you should be able to try.

**Comment by Nohus** [comment]
I am still hitting the issue on `layers`, but I'm not even sure if it's the same issue, because it seems there are also other problems. The map started blank until I figured out to zoom out far enough. Probably the correct level does not render at all for some reason.

**Comment by peterLaurence** [comment]
Strange, because I couldn't reproduce on layers. The demos work fine. Sure, we won't discuss layers here. I believe it's reasonable to only fix issues based on what we can reproduce in demos, otherwise it's too cumbersome. I'll continue on layers and we'll figure out later in appropriate issues.
