### ISSUE TITLE
Layers tiles visibility

### ISSUE THREAD

**Issue by peterLaurence** [peterLaurence/MapCompose#25]
> No tiles are drawn when scale >= 1. If I initialize the map with scale < 1 it works from the start, but as soon as it is scaled in past 1 tiles disappear. They show up again when it's scaled back.

**Comment by peterLaurence** [comment]
Can't reproduce in the demo ("Layers demo").
The max scale can be increased to 4. It still works in the demo.

**Comment by Nohus** [comment]
I will report back when I reproduce this in the demo app.

**Comment by peterLaurence** [comment]
And it's time for me to rest a bit.

**Comment by Nohus** [comment]
You can reproduce the bug on this branch: https://github.com/Nohus/MapCompose/tree/bug_reproduction
Enter the `SimpleDemo`.

**Comment by peterLaurence** [comment]
I've seen multiple issues, which I'm about to fix. This demo is the best way to share proof of an issue. As I'm able to reproduce it, I can investigate methodically. Surprising that the current demo isn't affected, but there must be an explanation - I'm not there yet.

**Comment by peterLaurence** [comment]
The biggest issue is that in the `layers` branch, I tried to switch to using RGB_565 bitmap configuration by default, which uses half memory as ARGB_8888 (the default). It really has an impact on performance. For maps, is perfectly acceptable to use RGB_565 since we're not displaying photos or content which requires high fidelity color. 
Using RGB_565 worked for the tiles in the upstream demo.
But your tiles, somehow can't be decoded into RGB_565 (when at full scale). The decoder requires bitmaps with twice as much size that would require a decoding using RGB_565. That's at full scale. However, when the scale is below 1, MapCompose sub-samples tiles. That's why the tiles fit in the available tiles (tile pool) when sub-sampling. That explains why tiles could only be loaded for scale < 1.
I reverted my change, and I'll add a way to opt-in to RGB_565 with due warning in the documentation.

**Comment by Nohus** [comment]
My tiles contains an alpha channel, maybe that's why? `RGB_565` does not have an alpha channel.

**Comment by peterLaurence** [comment]
This is probably the reason, indeed.

**Comment by peterLaurence** [comment]
Anyway, I reverted to using ARGB_8888 by default

**Comment by Nohus** [comment]
Can confirm this is fixed, can be closed.
