### ISSUE TITLE
Creating a new MapState breaks gestures

### ISSUE THREAD

**Issue by Nohus** [peterLaurence/MapCompose#33]
If you try this in the demo app:

```Kotlin
var state: MapState by mutableStateOf(createMapState())

init {
    viewModelScope.launch {
        delay(5000)
        state = createMapState()
    }
}
```

You can see that after the `MapState` is recreated the map no longer reacts to user interaction (scroll, zoom, etc.).
Recreating `MapState` is needed to switch between different maps (with different sizes, levels).

**Comment by peterLaurence** [comment]
Actually, what I've done on `v2` to fix this creates other problems. Consider this as not fixed.
