### ISSUE TITLE
scrollTo could use a simpler version

### ISSUE THREAD

**Issue by Nohus** [peterLaurence/MapCompose#35]
In other libraries there is usually a difference between `scrollTo()` and `smoothScrollTo()`/`animateScrollTo()`. In MapCompose there is only the animated version, which requires the use of a `SnapSpec` animation to achieve an instant move. I would propose to rename `scrollTo()` to `animateScrollTo()`, and create a new `scrollTo()` which is instant. A use case for a non-animated move for me is moving to an initial map position, or restoring the map position when changing the map type (which is a new `MapState`). Both should be instant, and using a 0-length animation feels like a hack.

The `setScroll()` method exists, but it has a less nice lower-level API not really suitable for user code.

I am proposing this before `v2` comes out which is a breaking change anyway.

Alternatively, it would be nice if `MapState` accepted an initial scroll position as a constructor argument, but that's a different issue. (I still think this would be good even if `MapState` did.)

**Comment by peterLaurence** [comment]
As of now, there's indeed no trivial way to scroll to a position (using normalized coordinates) without animating the scroll.
Using "smooth" in APIs or not is something I've considered. Most often, when users want to scroll they mean the animated scroll. A collection of APIs starting with "smooth", while reasonably readable, isn't as straightforward as a verb (like "scrollTo"). But it's not just about readability, it's mostly about most common usage.

For the particular case of scrolling without animating, I would prefer a new `snapScrollTo` API. The benefit is the scroll APIs are consistent with rotation APIs. While we're able to set the rotation without animation using the `rotation` property, the animated version is also named `rotateTo`.

For the initial scroll position, the use case would be the same as we do now for animated scroll:

```
MapState(4, 4096, 4096).apply {
    viewModelScope.launch {
        snapScrollTo(0.5, 0.5, 1f)
    }
}
```

Ideally, I'd like to avoid adding more arguments the `MapState` constructor (in order not to clutter it). In that regard, removing the `tileStreamProvider` was good move. `magnifyingFactor` feels out of place, but on the other hand it makes sense for the initial value. So yes, something should be done for initial values (and without cluttering the constructor). But that's a different issue.

What do you think?

**Comment by peterLaurence** [comment]
I forgot to mention migration. If we change the behavior of existing APIs (`scrollTo` becoming non-animated), migrating to v2 would be tricky as there would no compiler issue while the behavior changes.

**Comment by Nohus** [comment]
I gave it a go to see how it could look, what do you think?

**Comment by peterLaurence** [comment]
Looks good to me, I let you merge it ;)
