### ISSUE TITLE
Confusing map levels explanation image

### ISSUE THREAD

**Issue by Nohus** [peterLaurence/MapCompose#6]
The library assumes each level is twice as big as the previous one. After a 2 tiles wide level, the next level will be 4 tiles wide, and the next will be 8 tiles wide. However the explanation image in the documentation shows a 2 tiles wide level being followed with a 3 tiles wide level, and then 5 tiles wide level, which is not how the library works, and a source of confusion on how should I be generating my tiles.

![](https://github.com/peterLaurence/MapCompose/raw/master/doc/readme-files/deepzoom.png)

**Comment by peterLaurence** [comment]
I'm aware of it. Thanks for pointing this out.

**Comment by Nohus** [comment]
Image was updated.
